"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BiSolidDashboard } from "react-icons/bi";
import { usePathname } from "next/navigation";
import Link from "next/link";
import Button from "@/components/Button";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const pathname = usePathname()
    console.log("🚀 ~ RootLayout ~ pathname:", pathname)

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className='w-full h-screen fixed flex gap-2 '>
                    <div className='w-[15%] lg:w-[25%] xl:w-[18%] lg:flex flex-col  gap-4 py-20 pl-6 bg-gray-200 hidden'>

                        <h1 className='font-bold text-3xl'>LOGO</h1>
                        <Link href={'/dashboard'}>

                            <div className={`w-[80%]  flex gap-3 items-center rounded-lg p-2 ${pathname == "/dashboard" ? "bg-white" : ''}  `}>
                                <div className={`p-2 rounded-lg ${pathname === "/dashboard" ? " bg-blue-800" : ""} `}>
                                    <BiSolidDashboard className=' text-black text-2xl ' color={`${pathname == "/dashboard" ? "white" : 'black'}`} />
                                </div>
                                <div>
                                    <h1>Home</h1>
                                </div>
                            </div>
                        </Link>
                        <Link href={'/table'}>
                            <div className={`w-[80%] flex gap-3 items-center  rounded-lg p-2  ${pathname == "/table" ? "bg-white" : ''} `}>
                                <div className={`p-2 rounded-lg ${pathname == "/table" ? " bg-blue-800" : ""}`}>
                                    <BiSolidDashboard className=' text-black  text-2xl' color={`${pathname == "/table" ? "white" : 'black'}`} />
                                </div>
                                <div>
                                    <h1>Table</h1>
                                </div>
                            </div>
                        </Link>
                        <Link href={'/billing'}>
                            <div className={`w-[80%] flex gap-3 items-center  rounded-lg p-2  ${pathname == "/billing" ? "bg-white" : ''} `}>
                                <div className={`p-2 rounded-lg ${pathname == "/billing" ? " bg-blue-800" : ""}`}>
                                    <BiSolidDashboard className=' text-black  text-2xl' color={`${pathname == "/billing" ? "white" : 'black'}`} />
                                </div>
                                <div>
                                    <h1>billing</h1>
                                </div>
                            </div>
                        </Link>
                        <Link href={'/rtf'}>
                            <div className={`w-[80%] flex gap-3 items-center  rounded-lg p-2  ${pathname == "/rtf" ? "bg-white" : ''} `}>
                                <div className={`p-2 rounded-lg ${pathname == "/rtf" ? " bg-blue-800" : ""}`}>
                                    <BiSolidDashboard className=' text-black  text-2xl' color={`${pathname == "/rtf" ? "white" : 'black'}`} />
                                </div>
                                <div>
                                    <h1>RTF</h1>
                                </div>
                            </div>
                        </Link>



                        <h1>Account pages</h1>
                        <div className='flex flex-col gap-3'>


                            <div className='w-[80%] flex gap-3 items-center  rounded-lg p-2  ${pathname == "/"} '>
                                <div className='bg-white  p-2 rounded-lg'>
                                    <BiSolidDashboard className=' text-black  text-2xl' color='black' />
                                </div>
                                <div>
                                    <h1>RTL</h1>
                                </div>
                            </div>
                            <div className='w-[80%] flex gap-3 items-center  rounded-lg p-2  ${pathname == "/"} '>
                                <div className='bg-white  p-2 rounded-lg'>
                                    <BiSolidDashboard className=' text-black  text-2xl' color='black' />
                                </div>
                                <div>
                                    <h1>RTL</h1>
                                </div>
                            </div>
                            <div className='w-[80%] flex gap-3 items-center  rounded-lg p-2  ${pathname == "/"} '>
                                <div className='bg-white  p-2 rounded-lg'>
                                    <BiSolidDashboard className=' text-black  text-2xl' color='black' />
                                </div>
                                <div>
                                    <h1>RTL</h1>
                                </div>
                            </div>
                            <div className="w-[80%] h-[190px] flex flex-col justify-center p-4 gap-1 bg-gradient-to-l from-blue-400 to-blue-500 rounded-xl shadow-lg">
                                <div className="p-1 bg-white w-fit rounded-lg">
                                <BiSolidDashboard className=' text-white text-2xl' color='black' />
                                </div>
                                <div>
                                <h1 className=' text-white'>Need Help?</h1>
                                <h1 className=' text-white'>Please check our docs</h1>

                                </div>
                                <Button
                                    name={'DOCUMENTATION'}
                                    className={' rounded-lg'}
                                    bgcolor={"bg-blue-600 text-white text-xs"}
                                />
                            </div>
                        </div>

                    </div>
                    <div className='w-full sm:w-full  md:w-full   flex-col bg-gray-200 overflow-scroll'>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
